---
- name: Update package cache (for yum)
  yum:
    name: '*'
    state: latest
  when: ansible_pkg_mgr == 'yum'

- name: Install basic packages
  yum:
    name: "{{ item }}"
    state: present
  

- name: Install Java
  yum:
    name: java-11-openjdk-devel
    state: present

