---
- name: Download Long Term Jenkins release
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo


    
- name: Yum update
  yum:
    name: '*'
    state: latest

- name: Install Java
  yum:
    name: java-11-openjdk-devel
    state: present
    
- name: Yum update
  yum:
    name: '*'
    state: latest
    
- name: Import Jenkins key from URL
  ansible.builtin.rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
      #  when: ansible_pkg_mgr == 'yum'

- name: Install Jenkins
  yum:
    name: jenkins
    state: latest

- name: Daemon-reload to pick up config changes
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Start Jenkins
  ansible.builtin.systemd:
    name: jenkins
    state: started

